// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `describe`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartCall`, `DartQrtrSocket`, `QrtrSocketError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `address`, `fmt`, `fmt`, `receive`, `send`

/// Open a QMI session over the QRTR bus, through a socket Dart holds.
///
/// The app may not open a socket on the bus: SELinux refuses it one of its own,
/// and refuses it the use of one another process opened. The socket therefore
/// stays in the process Shizuku runs, and these three calls are the whole of
/// what the transport needs from it — where the socket is addressed, send this
/// datagram there, wait for one to come back — which is what the Dart side
/// implements over the channel to that process.
Future<ModemSession> openQmiQrtrSession({
  required FutureOr<QrtrSocketAddress> Function() address,
  required FutureOr<void> Function(QrtrSocketDatagram) send,
  required FutureOr<QrtrSocketDatagram?> Function(int) receive,
}) => RustLib.instance.api.crateApiModemOpenQmiQrtrSession(
  address: address,
  send: send,
  receive: receive,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModemSession>>
abstract class ModemSession implements RustOpaqueInterface {
  Future<void> closeChannel({required int slot, required int channel});

  Future<int> openChannel({required int slot, required List<int> aid});

  Future<Uint8List> reset({required int slot});

  Future<List<ModemSlot>> state();

  Future<Uint8List> transmit({
    required int slot,
    required int channel,
    required List<int> apdu,
  });
}

/// One card the modem sees.
class ModemSlot {
  /// Slot number, counted from one.
  final int slot;
  final bool present;
  final bool ready;
  final String? imei;
  final Uint8List? atr;

  const ModemSlot({
    required this.slot,
    required this.present,
    required this.ready,
    this.imei,
    this.atr,
  });

  @override
  int get hashCode =>
      slot.hashCode ^
      present.hashCode ^
      ready.hashCode ^
      imei.hashCode ^
      atr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModemSlot &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          present == other.present &&
          ready == other.ready &&
          imei == other.imei &&
          atr == other.atr;
}

/// Where a datagram is going, or came from: a node and a port on the bus.
class QrtrSocketAddress {
  final int node;
  final int port;

  const QrtrSocketAddress({required this.node, required this.port});

  @override
  int get hashCode => node.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrtrSocketAddress &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          port == other.port;
}

/// One datagram on the bus.
class QrtrSocketDatagram {
  /// Address it is for, or came from.
  final int node;
  final int port;
  final Uint8List data;

  const QrtrSocketDatagram({
    required this.node,
    required this.port,
    required this.data,
  });

  @override
  int get hashCode => node.hashCode ^ port.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrtrSocketDatagram &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          port == other.port &&
          data == other.data;
}
